apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: phpmyadmin
  type: NodePort
#LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: docker.iranserver.com/phpmyadmin/phpmyadmin
        env:
        - name: PMA_HOST
          value: wordpress-mysql
        - name: PMA_USER
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: username
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: sessions
          mountPath: /sessions
      volumes:
      - name: sessions
        emptyDir: {}
