apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
#  externalIPs:
#   - 192.168.1.1
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
