apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: wordpress
          image: docker.iranserver.com/library/wordpress
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              value: your_mysql_password
            - name: WORDPRESS_DB_NAME
              value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: ClusterIP
#  externalIPs:
#   - 192.168.1.1
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081

