apiVersion: v1
kind: Namespace
metadata:
  name: demo-app-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: demo-app-ns
data:
  database-name: demo-db
  database-user: db_user

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: demo-app-ns
type: Opaque
data:
  root-password: bXlzZWNyZXRwYXNzd29yZA==
  user-password: bXlzZWNyZXRwYXNzd29yZA==
